<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Property Management</name>
   <tag></tag>
   <elementGuidId>31294d03-3b50-48bc-b58b-d3f02542546b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-BackToPMA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-BackToPMA']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9e4fe16e-7b19-423e-b674-b2072d0d2adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-BackToPMA</value>
      <webElementGuid>a7eee793-22ca-4d07-9204-74397e3b1f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Property Management</value>
      <webElementGuid>be89058e-f046-4587-8ae6-30774d4649ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-BackToPMA&quot;)</value>
      <webElementGuid>2155df40-64a3-4239-aee9-909f5b811e21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-BackToPMA']</value>
      <webElementGuid>bd44dc74-1d60-4480-b55a-c902fef9d506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-PageLinks']/div</value>
      <webElementGuid>b5c48f03-c79e-499f-bcef-a10f0b365cc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/preceding::div[4]</value>
      <webElementGuid>b338fe41-9670-4008-a352-fec8f4efb89e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div</value>
      <webElementGuid>2653a296-3874-4348-83ee-e24098e81024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-BackToPMA' and (text() = 'Property Management' or . = 'Property Management')]</value>
      <webElementGuid>e66727ef-3fbb-43fa-af05-c247e8de07a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
