<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email</name>
   <tag></tag>
   <elementGuidId>8e9ad9fc-6d3b-4b71-a2b8-80b8c072ea76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[placeholder=&quot;Email&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@placeholder = 'Email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c47f8cd5-3f25-4d25-b68c-2e90d9a042a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>6451e25b-57d0-4fdc-b488-009fb8e87d78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9da361b3-7d75-42f4-9b85-4700afc3618d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>96e37c3c-be19-4802-996b-aa1e1daca62b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>f5181f25-89f4-4dbc-8048-a20094ee42e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-Input_Email2</value>
      <webElementGuid>4423ef67-891c-44f0-b570-61bbebb52503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-ca86d1a8be33b89c7aef886eb4c15ac6</value>
      <webElementGuid>a2b82181-d1cc-4369-b8d8-35b3b80ab48a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@placeholder = 'Email']</value>
      <webElementGuid>f6800f81-5d3c-49ae-be93-5c8013b8c711</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@placeholder = 'Email']</value>
      <webElementGuid>09982ab1-6170-42e1-94d6-db70086dc1aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Email' and @id = 'b2-Input_Email2']</value>
      <webElementGuid>c13b66c6-d19c-44f8-998d-31209e4c3b63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
